### ISSUE TITLE
Cleanup stable-v0.5 branch

### ISSUE THREAD

**Issue by Wenzel** [IntelLabs/kAFL#184]
The kAFL [`stable-v0.5`](https://github.com/IntelLabs/kAFL/tree/stable-v0.5) branch was established to get a stable pinned version of kAFL for the ccc repo.

However, even if the ccc repo's [`requirements.yml`](https://github.com/intel/ccc-linux-guest-hardening/blob/master/deploy/requirements.yml#L5) refers to this branch, the variables defined in the branch's [`site.yml`](https://github.com/IntelLabs/kAFL/blob/stable-v0.5/deploy/site.yml#L17)
```YAML
    - role: intellabs.kafl.fuzzer
      tags:
        - fuzzer
      vars:
        # branches maintained for this version
        - fuzzer_revision: 'v0.5.1'
        - qemu_revision: 'kafl-v0.5'
        - examples_revision: 'v0.1'
        # no maintained branch - try latest
        # - libxdc_revision:     'ec596317'
        # - capstone_revision:   '0efa3cc5'
        # - radamsa_revision:    'df651a67'
        # - nyx_packer_revision: 'ef990c60'
```

Are actually overriden by the [`bkc`](https://github.com/intel/ccc-linux-guest-hardening/blob/master/deploy/roles/bkc/meta/main.yml) role from the ccc repo:

```YAML
dependencies:
  - role: intellabs.kafl.fuzzer
    tags:
      - fuzzer
    vars:
      fuzzer_revision: kafl_tdx
      qemu_revision: kafl_stable_tdx
      libxdc_revision: kafl_stable_tdx
```

The changes brought by `kafl_tdx` branch on `kafl.fuzzer`:
https://github.com/IntelLabs/kafl.fuzzer/compare/v0.5.1...kafl_tdx

The changes brought by `kafl_stable_tdx` on `kafl.qemu`:
https://github.com/IntelLabs/kafl.qemu/compare/kafl-v0.5...kafl_stable_tdx
